export enum AuthActionNames {
    SET_USERNAME = "AUTH/SET_USERNAME",
    SET_ACCESSTOKEN = "AUTH/SET_ACCESSTOKEN",
    SET_FULLNAME = "AUTH/SET_FULLNAME",
    SET_OCCUPATION = "AUTH/SET_OCCUPATION",
    RESET = "AUTH/RESET"
}

